### ISSUE TITLE
Error when clearing cache on installing meter in Mac OS

### ISSUE THREAD

**Issue by pbvignesh** [sarfraznawaz2005/meter#1]
- Laravel Version - 5.6.39
- PHP Version - 7.2.25
- OS - MacOS Mojave Version 10.14.3

**Description**
After installing meter on Mac and publishing, when you try running CLI commands such as php artisan migrate:status, php artisan cache:clear etc, it throws the following error

![Screenshot 2020-01-27 at 3 26 38 PM](https://user-images.githubusercontent.com/15857119/73165246-75872380-4119-11ea-9df6-66560f6a830e.png)

The issue happens in MemoryMonitor.php where we try to run the _free_ command. However I don't think Mac OS Supports the free command and as a result it returns an empty value. Either we need to provide support for Mac or add error handling

@sarfraznawaz2005 Can you let me know what is the purpose of the MemoryMonitor class so that I can add a patch and submit a pull request for this ? Does it just get the percent of memory free / used etc

**Comment by sarfraznawaz2005** [comment]
Hi,

Can you please try updating the package as I just made few fixes and pushed.

The Memory monitor actually sees server RAM usage. This is of course supposed to run on linux but if you still receive any error after updating, I will put OS check there then.
