### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by eelco2k** [sarfraznawaz2005/meter#5]
vendor/sarfraznawaz2005/meter/src/Tables/Table.php:52 and
vendor/sarfraznawaz2005/meter/src/Tables/Table.php:53

in the request the request()->order is not set in request by default

**Comment by sarfraznawaz2005** [comment]
Can you please tell laravel version ? Which page this is happening on ? Also have you modified anything in the package code ?

**Comment by syzygyinteractivemedia** [comment]
Laravel version 6.0,  on every page where an datatables table is loaded. I haven't modified the code.

When i changed line 52 and 53 with an isset(request()->order) check then it works but i cannot change columnorder of the datatables on the frontend.

**Comment by sarfraznawaz2005** [comment]
Please try updating to latest version 1.0.7. thx

**Comment by syzygyinteractivemedia** [comment]
thnx it's working now as expected
